version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
